import math
import grafo 

g = grafo.grafo()
g.agregarVertice(1)
g.agregarVertice(2)
g.agregarVertice(3)
g.agregarVertice(4)
g.agregarVertice(5)
g.agregarVertice(6)
g.agregarArista(1, 6, 14)
g.agregarArista(1, 2, 7)
g.agregarArista(1, 3, 9)
g.agregarArista(2, 3, 10)
g.agregarArista(2, 4, 15)
g.agregarArista(3, 4, 11)
g.agregarArista(3, 6, 2)
g.agregarArista(4, 5, 6)
g.agregarArista(5, 6, 9)
# print("\n\nLa ruta mas rapida por Dijkstra junto con su costo es:")
# g.dijkstra(1)
# print(g.camino(1, 5))
# print("\nLos valores finales de la grafica son los siguietes:")
# g.imprimir()

g.dibujar_grafo()